include:
  - component: $CI_SERVER_FQDN/home-lab/automations/docker-compose-service-deployment@v2.0.5
    inputs:
      vm-hostname: infrastructure.vm.xbhl.intranet
      vm-ssh-username: $SSH_USER
      vm-ssh-private-key: $SSH_PRIVATE_KEY
      service-name: whats-up-docker
      container-name: whats-up-docker
      container-location: /opt/containers/whats-up-docker
      cloudflare-dns-entry-name: wud.intranet.xbhl.online
      cloudflare-zone-id: $CLOUDFLARE_ZONE_ID
      cloudflare-dns-api-token: $CLOUDFLARE_DNS_API_TOKEN
      cloudflare-dns-strategy: "direct"
      delete-existing-container-files: true

setup:generate-build-artifacts:
  script:
    - cp -r src/envs $BUILD_ARTIFACTS_DIR/
    - sed -i "s|^WUD_AUTH_OIDC_AUTHELIA_CLIENTSECRET=.*|WUD_AUTH_OIDC_AUTHELIA_CLIENTSECRET=${WUD_OAUTH_CLIENT_SECRET}|" $BUILD_ARTIFACTS_DIR/envs/auth/authelia.env
    - sed -i "s|^WUD_TRIGGER_SMTP_MAIL_HOST=.*|WUD_TRIGGER_SMTP_MAIL_HOST=${SMTP_HOST}|" $BUILD_ARTIFACTS_DIR/envs/triggers/smtp.env
    - sed -i "s|^WUD_TRIGGER_SMTP_MAIL_PORT=.*|WUD_TRIGGER_SMTP_MAIL_PORT=${SMTP_PORT}|" $BUILD_ARTIFACTS_DIR/envs/triggers/smtp.env
    - sed -i "s|^WUD_TRIGGER_SMTP_MAIL_USER=.*|WUD_TRIGGER_SMTP_MAIL_USER=${SMTP_USERNAME}|" $BUILD_ARTIFACTS_DIR/envs/triggers/smtp.env
    - sed -i "s|^WUD_TRIGGER_SMTP_MAIL_PASS=.*|WUD_TRIGGER_SMTP_MAIL_PASS=${SMTP_PASSWORD}|" $BUILD_ARTIFACTS_DIR/envs/triggers/smtp.env
    - sed -i "s|^WUD_TRIGGER_SMTP_MAIL_FROM_ADDRESS=.*|WUD_TRIGGER_SMTP_MAIL_FROM_ADDRESS=${SMTP_FROM}|" $BUILD_ARTIFACTS_DIR/envs/triggers/smtp.env
    - if [ "$SMTP_PORT" = "465" ]; then sed -i "s|^WUD_TRIGGER_SMTP_MAIL_TLS_ENABLED=.*|WUD_TRIGGER_SMTP_MAIL_TLS_ENABLED=true|" $BUILD_ARTIFACTS_DIR/envs/triggers/smtp.env; else sed -i "s|^WUD_TRIGGER_SMTP_MAIL_TLS_ENABLED=.*|WUD_TRIGGER_SMTP_MAIL_TLS_ENABLED=false|" $BUILD_ARTIFACTS_DIR/envs/triggers/smtp.env; fi
