services:
  whats-up-docker:
    image: getwud/wud@sha256:eb2d8522f09ccbb5f350ecb481fe5342fefd8b48335f5f787000ffeccc118881
    container_name: whats-up-docker
    hostname: whats-up-docker.ctr.xbhl.intranet
    environment:
      TZ: Europe/Warsaw
      WUD_LOG_LEVEL: INFO
    env_file:
      - envs/auth/authelia.env
      # triggers
      - envs/triggers/smtp.env
      - envs/triggers/discord.env
      - envs/triggers/mqtt.env
      # watchers
      - envs/watchers/infrastructure.vm.xbhl.intranet.env
      - envs/watchers/cloud.vm.xbhl.intranet.env
      - envs/watchers/code.vm.xbhl.intranet.env
      - envs/watchers/dns.vm.xbhl.intranet.env
      - envs/watchers/ha.vm.xbhl.intranet.env
      - envs/watchers/media.vm.xbhl.intranet.env
      - envs/watchers/nas.srv.xbhl.intranet.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - store:/store
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --spider http://127.0.0.1:3000/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whats-up-docker-router.rule=Host(`wud.intranet.xbhl.online`)"
      - "traefik.http.routers.whats-up-docker-router.entrypoints=websecure"
      - "traefik.http.routers.whats-up-docker-router.tls=true"
      - "traefik.http.routers.whats-up-docker-router.service=whats-up-docker"
      - "traefik.http.services.whats-up-docker.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
      - 'wud.watch=true'
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
      - "wud.link.template=https://github.com/getwud/wud/releases/tag/$${major}.$${minor}.$${patch}"
    networks:
      - proxy
    restart: unless-stopped

volumes:
  store:

networks:
  proxy:
    external: true
